// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkkshibjrjhdoobsrqdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impra3NoaWJqcmpoZG9vYnNycWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODkyMjMsImV4cCI6MjA2NTY2NTIyM30.TgLYdtU9MTK7mHl0dzgal1IxsvQE1Pi0d1Adc5sS3lM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);